[connections.snowflake]
user = "survey_user"
password = "Shunkhlai123!"
account = "DO04924"
warehouse = "cdna_wh_s"
database = "CDNA_HR_DATA"
schema = "APU"
role = "survey_role"  # Optional but recommended
